keys:
  - &host age1x3emg36yt6tlmzhc2ehjg67ng22fyq0k0f3zcae2uvcn8htjxa8su9zfpp
  - &user age1gr94up3jqnspxlxrac3r6927kuvfepe6qvpvltduzjhs6gstk3esr7dvgj
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - pgp: []
        age:
          - *host
          - *user
