# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.zswap = {
    enable = true; # /sys/module/zswap/parameters/enabled
    compressor = "zstd"; # lz4 | zstd | lzo (默认 lz4)
    zpool = "zsmalloc"; # zbud | z3fold
    maxPoolPercent = 20; # 最大占用物理内存百分比
    shrinkerEnabled = true; # 允许压缩池被 shrinker 回收
    acceptThresholdPercent = 25; # 填充到此阈值时才启用压缩写入
  };

  fileSystems."/" = {
    device = "/dev/mapper/sgnay-root";
    fsType = "btrfs";
    options = [ "subvol=@root" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/sgnay-data";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0D91-1407";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home/sdata" = {
    device = "/dev/disk/by-uuid/0A083C6B083C5841";
    fsType = "ntfs3";
    options = [ "nofail" ];
  };

  swapDevices = [
    {
      device = "/dev/mapper/sgnay-swap";
      options = [ "discard" ];
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
